"""add_categories_and_podcasts_tables

Revision ID: 447fcfec14c4
Revises: 6a09531a5fb7
Create Date: 2025-10-03 22:18:45.318359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447fcfec14c4'
down_revision = '6a09531a5fb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
