"""add_google_oauth_fields

Revision ID: ff1d41cdfaef
Revises: 46dfbc857af9
Create Date: 2025-10-03 11:09:55.316798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1d41cdfaef'
down_revision = '46dfbc857af9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
